# Std
import os
import numpy
import pandas

# Mine
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

class LinesPlotter():
    def __init__(self, plot_specs):
        self.plot_specs = plot_specs

    def plotInPath(self, plot_path_without_extension):
        footer_artist = setupPlot(self.plot_specs.setup_specs)
        # ADAPTAR: (BORRAR/MOVER A LinesPlotter)

        # Define legend
        lgd = plt.legend(loc="center left", fontsize="small", fancybox=True, shadow=True,
                         bbox_to_anchor=(1, 0.5))

        # Post-line-plot setup
        setupXTicks(self.plot_specs.setup_specs.extra_ticks)
        saveAndClearPlt(plot_path_without_extension, lgd, footer_artist)
        # ADAPTAR^ (BORRAR/MOVER A LinesPlotter)


def setupPlot(setup_specs):
    plt.style.use('fivethirtyeight')
    plt.gca().set_position([0.10, 0.15, 0.80, 0.77])
    plt.xlabel(setup_specs.x_label)
    plt.title(setup_specs.title + "\n" + setup_specs.subtitle, fontsize=14, y=1.08)
    plt.ylabel(setup_specs.y_label)
    plt.ticklabel_format(useOffset=False)  # So it doesn't use an offset on the x axis
    footer_artist = plt.annotate(setup_specs.footer, (1, 0), (0, -70), xycoords='axes fraction', textcoords='offset points',
                                 va='top', horizontalalignment='right')
    plt.margins(x=0.1, y=0.1)  # increase buffer so points falling on it are plotted
    return footer_artist


def setupXTicks(extra_ticks):
    # Get the ticks automatically generated by matplotlib
    auto_x_ticks = list(plt.xticks()[0])
    # Trim the borders (excessively large)
    auto_x_ticks_wo_borders = auto_x_ticks[1:-1]
    x_ticks = sorted(auto_x_ticks_wo_borders + extra_ticks)
    plt.xticks(x_ticks, rotation='vertical')  # add extra ticks (1975 for vermeulen for example)


def saveAndClearPlt(plot_path_without_extension, lgd, footer_artist, extra_lgd=None):
    extensions = [".svg", ".png"]
    for ext in extensions:
        plot_path = plot_path_without_extension + ext
        if extra_lgd:
            # If two legends (for when the plot has variables with different scale)
            plt.savefig(plot_path, bbox_extra_artists=(lgd, extra_lgd, footer_artist), bbox_inches='tight')
        else:
            # If only one legend
            plt.savefig(plot_path, bbox_extra_artists=(lgd, footer_artist), bbox_inches='tight')
    plt.clf()
