# Based on "standard_run_params_defaults.csv". Written as python code for
#  easier use and because this list is unlikely to change

# Pairs meaning:
#    Parameter name, value
w3_params_info_list = [("agr_inp_init",5000000000.0),
                        ("agr_mtl_toxic_index",1.0),
                        ("arable_land_init",900000000.0),
                        ("assim_half_life_1970",1.5),
                        ("avg_life_land_norm",1000.0),
                        ("des_compl_fam_size_norm",3.8),
                        ("des_food_ratio_dfr",2.0),
                        ("des_ppoll_index_DPOLX",1.2),
                        ("des_res_use_rt_DNRUR",4800000000.0),
                        ("food_short_perc_del",2.0),
                        ("fr_agr_inp_pers_mtl",0.001),
                        ("frac_res_pers_mtl",0.02),
                        ("hlth_serv_impact_del",20.0),
                        ("income_expect_avg_time",3.0),
                        ("ind_mtl_emiss_fact",0.1),
                        ("ind_mtl_toxic_index",10.0),
                        ("ind_out_in_1970",790000000000.0),
                        ("ind_out_pc_des",400.0),
                        ("industrial_capital_init",210000000000.0),
                        ("inherent_land_fert",600.0),
                        ("labor_force_partic",0.75),
                        ("labor_util_fr_del_init",1.0),
                        ("labor_util_fr_del_time",2.0),
                        ("land_fertility_init",600.0),
                        ("land_fr_harvested",0.7),
                        ("life_expect_norm",28.0),
                        ("lifet_perc_del",20.0),
                        ("max_tot_fert_norm",12.0),
                        ("nr_resources_init",1000000000000.0),
                        ("p_avg_life_agr_inp_1",2.0),
                        ("p_avg_life_agr_inp_2",2.0),
                        ("p_avg_life_ind_cap_1",14.0),
                        ("p_avg_life_ind_cap_2",14.0),
                        ("p_avg_life_serv_cap_1",20.0),
                        ("p_avg_life_serv_cap_2",20.0),
                        ("p_fioa_cons_const_1",0.43),
                        ("p_fioa_cons_const_2",0.43),
                        ("p_fr_cap_al_obt_res_2[1]",1.0),
                        ("p_fr_cap_al_obt_res_2[2]",0.2),
                        ("p_fr_cap_al_obt_res_2[3]",0.1),
                        ("p_fr_cap_al_obt_res_2[4]",0.05),
                        ("p_fr_cap_al_obt_res_2[5]",0.05),
                        ("p_fr_cap_al_obt_res_2[6]",0.05),
                        ("p_fr_cap_al_obt_res_2[7]",0.05),
                        ("p_fr_cap_al_obt_res_2[8]",0.05),
                        ("p_fr_cap_al_obt_res_2[9]",0.05),
                        ("p_fr_cap_al_obt_res_2[10]",0.05),
                        ("p_fr_cap_al_obt_res_2[11]",0.05),
                        ("p_ind_cap_out_ratio_1",3.0),
                        ("p_land_yield_fact_1",1.0),
                        ("p_nr_res_use_fact_1",1.0),
                        ("p_ppoll_gen_fact_1",1.0),
                        ("p_ppoll_tech_chg_mlt[1]",0.0),
                        ("p_ppoll_tech_chg_mlt[2]",0.0),
                        ("p_ppoll_tech_chg_mlt[3]",0.0),
                        ("p_ppoll_tech_chg_mlt[4]",0.0),
                        ("p_res_tech_chg_mlt[1]",0.0),
                        ("p_res_tech_chg_mlt[2]",0.0),
                        ("p_res_tech_chg_mlt[3]",0.0),
                        ("p_res_tech_chg_mlt[4]",0.0),
                        ("p_serv_cap_out_ratio_1",1.0),
                        ("p_serv_cap_out_ratio_2",1.0),
                        ("p_yield_tech_chg_mlt[1]",0.0),
                        ("p_yield_tech_chg_mlt[2]",0.0),
                        ("p_yield_tech_chg_mlt[3]",0.0),
                        ("p_yield_tech_chg_mlt[4]",0.0),
                        ("perc_food_ratio_init",1.0),
                        ("pers_pollution_init",25000000.0),
                        ("pop1_init",650000000.0),
                        ("pop2_init",700000000.0),
                        ("pop3_init",190000000.0),
                        ("pop4_init",60000000.0),
                        ("pot_arable_land_init",2300000000.0),
                        ("pot_arable_land_tot",3200000000.0),
                        ("ppoll_in_1970",136000000.0),
                        ("ppoll_tech_init",1.0),
                        ("ppoll_trans_del",20.0),
                        ("processing_loss",0.1),
                        ("reproductive_lifetime",30.0),
                        ("res_tech_init",1.0),
                        ("service_capital_init",144000000000.0),
                        ("social_adj_del",20.0),
                        ("social_discount",0.07000000000000001),
                        ("subsist_food_pc",230.0),
                        ("t_air_poll_time",4000.0),
                        ("t_fcaor_time",4000.0),
                        ("t_fert_cont_eff_time",4000.0),
                        ("t_ind_equil_time",4000.0),
                        ("t_land_life_time",4000.0),
                        ("t_policy_year",4000.0),
                        ("t_pop_equil_time",4000.0),
                        ("t_zero_pop_grow_time",4000.0),
                        ("tech_dev_del_TDD",20.0),
                        ("urb_ind_land_dev_time",10.0),
                        ("urban_ind_land_init",8200000.0),
                        ("yield_tech_init",1.0)]

om_TheoParamSensitivity_params_dict = {
             'agr_inp_init': 'P.1',
             'agr_mtl_toxic_index': 'P.2',
             'arable_land_init': 'P.3',
             'assim_half_life_1970': 'P.4',
             'avg_life_land_norm': 'P.5',
             'des_compl_fam_size_norm': 'P.6',
             'des_food_ratio_dfr': 'P.7',
             'des_ppoll_index_DPOLX': 'P.8',
             'des_res_use_rt_DNRUR': 'P.9',
             'food_short_perc_del': 'P.10',
             'fr_agr_inp_pers_mtl': 'P.11',
             'frac_res_pers_mtl': 'P.12',
             'hlth_serv_impact_del': 'P.13',
             'income_expect_avg_time': 'P.14',
             'ind_mtl_emiss_fact': 'P.15',
             'ind_mtl_toxic_index': 'P.16',
             'ind_out_in_1970': 'P.17',
             'ind_out_pc_des': 'P.18',
             'industrial_capital_init': 'P.19',
             'inherent_land_fert': 'P.20',
             'labor_force_partic': 'P.21',
             'labor_util_fr_del_init': 'P.22',
             'labor_util_fr_del_time': 'P.23',
             'land_fertility_init': 'P.24',
             'land_fr_harvested': 'P.25',
             'life_expect_norm': 'P.26',
             'lifet_perc_del': 'P.27',
             'max_tot_fert_norm': 'P.28',
             'nr_resources_init': 'P.29',
             'p_avg_life_agr_inp_1': 'P.30',
             'p_avg_life_agr_inp_2': 'P.31',
             'p_avg_life_ind_cap_1': 'P.32',
             'p_avg_life_ind_cap_2': 'P.33',
             'p_avg_life_serv_cap_1': 'P.34',
             'p_avg_life_serv_cap_2': 'P.35',
             'p_fioa_cons_const_1': 'P.36',
             'p_fioa_cons_const_2': 'P.37',
             'p_fr_cap_al_obt_res_2[10]': 'P.47',
             'p_fr_cap_al_obt_res_2[11]': 'P.48',
             'p_fr_cap_al_obt_res_2[1]': 'P.38',
             'p_fr_cap_al_obt_res_2[2]': 'P.39',
             'p_fr_cap_al_obt_res_2[3]': 'P.40',
             'p_fr_cap_al_obt_res_2[4]': 'P.41',
             'p_fr_cap_al_obt_res_2[5]': 'P.42',
             'p_fr_cap_al_obt_res_2[6]': 'P.43',
             'p_fr_cap_al_obt_res_2[7]': 'P.44',
             'p_fr_cap_al_obt_res_2[8]': 'P.45',
             'p_fr_cap_al_obt_res_2[9]': 'P.46',
             'p_ind_cap_out_ratio_1': 'P.49',
             'p_land_yield_fact_1': 'P.50',
             'p_nr_res_use_fact_1': 'P.51',
             'p_ppoll_gen_fact_1': 'P.52',
             'p_ppoll_tech_chg_mlt[1]': 'P.53',
             'p_ppoll_tech_chg_mlt[2]': 'P.54',
             'p_ppoll_tech_chg_mlt[3]': 'P.55',
             'p_ppoll_tech_chg_mlt[4]': 'P.56',
             'p_res_tech_chg_mlt[1]': 'P.57',
             'p_res_tech_chg_mlt[2]': 'P.58',
             'p_res_tech_chg_mlt[3]': 'P.59',
             'p_res_tech_chg_mlt[4]': 'P.60',
             'p_serv_cap_out_ratio_1': 'P.61',
             'p_serv_cap_out_ratio_2': 'P.62',
             'p_yield_tech_chg_mlt[1]': 'P.63',
             'p_yield_tech_chg_mlt[2]': 'P.64',
             'p_yield_tech_chg_mlt[3]': 'P.65',
             'p_yield_tech_chg_mlt[4]': 'P.66',
             'perc_food_ratio_init': 'P.67',
             'pers_pollution_init': 'P.68',
             'pop1_init': 'P.69',
             'pop2_init': 'P.70',
             'pop3_init': 'P.71',
             'pop4_init': 'P.72',
             'pot_arable_land_init': 'P.73',
             'pot_arable_land_tot': 'P.74',
             'ppoll_in_1970': 'P.75',
             'ppoll_tech_init': 'P.76',
             'ppoll_trans_del': 'P.77',
             'processing_loss': 'P.78',
             'reproductive_lifetime': 'P.79',
             'res_tech_init': 'P.80',
             'service_capital_init': 'P.81',
             'social_adj_del': 'P.82',
             'social_discount': 'P.83',
             'subsist_food_pc': 'P.84',
             't_air_poll_time': 'P.85',
             't_fcaor_time': 'P.86',
             't_fert_cont_eff_time': 'P.87',
             't_ind_equil_time': 'P.88',
             't_land_life_time': 'P.89',
             't_policy_year': 'P.90',
             't_pop_equil_time': 'P.91',
             't_zero_pop_grow_time': 'P.92',
             'tech_dev_del_TDD': 'P.93',
             'urb_ind_land_dev_time': 'P.94',
             'urban_ind_land_init': 'P.95',
             'yield_tech_init': 'P.96'}

om_TheoParamSensitivity_differentiableVariables_dict = {
      'Arable_Land_Dynamics1.Arable_Land.Integrator1.y': 'Vd.1',
      'Arable_Land_Dynamics1.Pot_Arable_Land.Integrator1.y': 'Vd.2',
      'Arable_Land_Dynamics1.Urban_Ind_Land.Integrator1.y': 'Vd.3',
      'Food_Production1.Agr_Inp.Integrator1.y': 'Vd.4',
      'Food_Production1.P_Land_Yield_Fact_2.Smooth1.Integrator1.y': 'Vd.5',
      'Food_Production1.P_Land_Yield_Fact_2.Smooth2.Integrator1.y': 'Vd.6',
      'Food_Production1.P_Land_Yield_Fact_2.Smooth3.Integrator1.y': 'Vd.7',
      'Food_Production1.Perc_Food_Ratio.Integrator1.y': 'Vd.8',
      'Human_Fertility1.Avg_Ind_Out_PC.Smooth_of_Input.Integrator1.y': 'Vd.9',
      'Human_Fertility1.Del_Ind_Out_PC.Smooth1.Integrator1.y': 'Vd.10',
      'Human_Fertility1.Del_Ind_Out_PC.Smooth2.Integrator1.y': 'Vd.11',
      'Human_Fertility1.Del_Ind_Out_PC.Smooth3.Integrator1.y': 'Vd.12',
      'Human_Fertility1.Fert_Cont_Facil_PC.Smooth1.Integrator1.y': 'Vd.13',
      'Human_Fertility1.Fert_Cont_Facil_PC.Smooth2.Integrator1.y': 'Vd.14',
      'Human_Fertility1.Fert_Cont_Facil_PC.Smooth3.Integrator1.y': 'Vd.15',
      'Human_Fertility1.Perc_Life_Expectancy.Smooth1.Integrator1.y': 'Vd.16',
      'Human_Fertility1.Perc_Life_Expectancy.Smooth2.Integrator1.y': 'Vd.17',
      'Human_Fertility1.Perc_Life_Expectancy.Smooth3.Integrator1.y': 'Vd.18',
      'Industrial_Investment1.Industrial_Capital.Integrator1.y': 'Vd.19',
      'Labor_Utilization1.Labor_Util_Fr_Del.Integrator1.y': 'Vd.20',
      'Land_Fertility1.Land_Fertility.Integrator1.y': 'Vd.21',
      'Land_Fertility1.Yield_Tech_LYTD.Integrator1.y': 'Vd.22',
      'Life_Expectancy1.Eff_Hlth_Serv_PC.Smooth_of_Input.Integrator1.y': 'Vd.23',
      'NR_Resource_Utilization1.NR_Resources.Integrator1.y': 'Vd.24',
      'NR_Resource_Utilization1.P_Nr_Res_Use_Fact_2.Smooth1.Integrator1.y': 'Vd.25',
      'NR_Resource_Utilization1.P_Nr_Res_Use_Fact_2.Smooth2.Integrator1.y': 'Vd.26',
      'NR_Resource_Utilization1.P_Nr_Res_Use_Fact_2.Smooth3.Integrator1.y': 'Vd.27',
      'NR_Resource_Utilization1.Res_Tech_NRTD.Integrator1.y': 'Vd.28',
      'Pollution_Dynamics1.PPoll_Appear_Rate.Smooth1.Integrator1.y': 'Vd.29',
      'Pollution_Dynamics1.PPoll_Appear_Rate.Smooth2.Integrator1.y': 'Vd.30',
      'Pollution_Dynamics1.PPoll_Appear_Rate.Smooth3.Integrator1.y': 'Vd.31',
      'Pollution_Dynamics1.PPoll_Tech_PTD.Integrator1.y': 'Vd.32',
      'Pollution_Dynamics1.P_PPoll_Gen_Fact_2.Smooth1.Integrator1.y': 'Vd.33',
      'Pollution_Dynamics1.P_PPoll_Gen_Fact_2.Smooth2.Integrator1.y': 'Vd.34',
      'Pollution_Dynamics1.P_PPoll_Gen_Fact_2.Smooth3.Integrator1.y': 'Vd.35',
      'Pollution_Dynamics1.Pers_Pollution.Integrator1.y': 'Vd.36',
      'Population_Dynamics1.Pop_0_14.Integrator1.y': 'Vd.37',
      'Population_Dynamics1.Pop_15_44.Integrator1.y': 'Vd.38',
      'Population_Dynamics1.Pop_45_64.Integrator1.y': 'Vd.39',
      'Population_Dynamics1.Pop_65plus.Integrator1.y': 'Vd.40',
      'Service_Sector_Investment1.Service_Capital.Integrator1.y': 'Vd.41'}
om_TheoParamSensitivity_differentiableVariablesExtra_dict = {
        "Population_Dynamics1.pop_state_var_new": "Vdextra.1",
        }

om_TheoParamSensitivity_nonDiffVars_dict = {
      "nr_resources": "Vnd.1",
      "population": "Vnd.2"
      }
